### ISSUE TITLE
Update Electron for Hatch-Previewer

### ISSUE THREAD

**Issue by nedrichards** [endlessm/libingester#122]
Hatch Previewer requires Electron 1.4.1, the latest release on that train is [1.4.15](https://electronjs.org/releases#1.4.15) the latest stable release is [1.7.12](https://electronjs.org/releases#1.7.12) which also has a number of security fixes.

**Comment by sgnn7** [comment]
https://github.com/endlessm/libingester/pull/124 Seems to work from some basic testing

**Comment by cosimoc** [comment]
Indeed it works (tested it yesterday). Closing :-)

**Comment by sgnn7** [comment]
Published to npm as v2.4.3
