### ISSUE TITLE
Flatpak hatch-previewer

### ISSUE THREAD

**Issue by nedrichards** [endlessm/libingester#123]
We would like a flatpak of hatch-previewer to more easily install and use on Endless systems.

We could either do this with the npm or yarn tools in [Flatpak-builder-tools](https://github.com/flatpak/flatpak-builder-tools/) to make a flatpak-builder manifest or use [Electron Installer Flatpak](https://github.com/endlessm/electron-installer-flatpak) to just spit out a Flatpak bundle. It's a bit more annoying to update though.

**Comment by ptomato** [comment]
This is flatpacked now, and available on Flathub. (There's some problem with the metadata which means it's only available to install using the command line client, but it's not clear whether that's a Flathub problem or a problem with the manifest.)

**Comment by sgnn7** [comment]
@ptomato Was ARM build ever fixed (or do we care about it)?

**Comment by ptomato** [comment]
Personally I don't care about that, but it would be nice to investigate if it turns out that other Electron apps do work correctly on ARM.

**Comment by sgnn7** [comment]
Fair enough - just wanted to see if it was important or not.

**Comment by nedrichards** [comment]
There's a more general issue with apps building on 32 bit arm that need more than 4Gb of RAM... Not Endless specific but we do want to fix because we ship arm products (and plan to ship more 32bit arm).
